apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.otelCollector.name }}
  labels:
    app: {{ .Values.otelCollector.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.otelCollector.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.otelCollector.name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8888" # OTEL metrics port (if enabled)
    spec:
      containers:
        - name: otel-collector
          image: "{{ .Values.otelCollector.image.repository }}:{{ .Values.otelCollector.image.tag }}"
          imagePullPolicy: {{ .Values.otelCollector.image.pullPolicy }}

          args:
            - "--config=/conf/otel-collector-config.yaml"

          ports:
            - name: otlp-grpc
              containerPort: {{ .Values.otelCollector.service.grpcPort }}
              protocol: TCP

            - name: otlp-http
              containerPort: {{ .Values.otelCollector.service.httpPort }}
              protocol: TCP

            - name: metrics
              containerPort: 8888
              protocol: TCP

          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"

          volumeMounts:
            - name: config
              mountPath: /conf

      volumes:
        - name: config
          configMap:
            name: {{ .Values.otelCollector.name }}-config
