apiVersion: v1
kind: Service
metadata:
  name: productcatalog
spec:
  type: {{ .Values.productcatalog.service.type }}
  selector:
    app: productcatalog
  ports:
    - port: {{ .Values.productcatalog.service.port }}
      targetPort: 8080

