apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalog
spec:
  replicas: {{ .Values.productcatalog.replicaCount }}
  selector:
    matchLabels:
      app: productcatalog
  template:
    metadata:
      labels:
        app: productcatalog
    spec:
      containers:
        - name: productcatalog
          image: "{{ .Values.productcatalog.image.repository }}:{{ .Values.productcatalog.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: Port
              value: "8080"

            # OPTIONAL: silence OTEL exporter for now

{{ include "otel.env" . | indent 12 }}

            - name: OTEL_SERVICE_NAME
              value: productcatalog

