apiVersion: v1
kind: Service
metadata:
  name: frontendproxy
spec:
  type: NodePort
  selector:
    app: frontendproxy
  ports:
    - port: {{ .Values.frontendproxy.service.port }}
      targetPort: {{ .Values.frontendproxy.service.port }}
