apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
spec:
  replicas: {{ .Values.adservice.replicaCount }}
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
        - name: adservice
          image: "{{ .Values.adservice.image.repository }}:{{ .Values.adservice.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
{{ include "otel.env" . | indent 12 }}
            - name: AD_SERVICE_PORT
              value: "8080"
            - name: OTEL_SERVICE_NAME
              value: adservice
