apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.otelCollector.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.otelCollector.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.otelCollector.name }}
    spec:
      containers:
        - name: otel-collector
          image: "{{ .Values.otelCollector.image.repository }}:{{ .Values.otelCollector.image.tag }}"
          imagePullPolicy: {{ .Values.otelCollector.image.pullPolicy }}
          args:
            - "--config=/conf/otel-collector-config.yaml"
          ports:
            - containerPort: {{ .Values.otelCollector.service.grpcPort }}
            - containerPort: {{ .Values.otelCollector.service.httpPort }}
          volumeMounts:
            - name: config
              mountPath: /conf
      volumes:
        - name: config
          configMap:
            name: {{ .Values.otelCollector.name }}-config
