apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  replicas: {{ .Values.cartservice.replicaCount }}
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: cartservice
          image: "{{ .Values.cartservice.image.repository }}:{{ .Values.cartservice.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: CART_SERVICE_PORT
              value: "8080"

            # OPTIONAL: silence OTEL exporter for now
            - name: VALKEY_ADDR
              value: "redis:6379"



{{ include "otel.env" . | indent 12 }}

            - name: OTEL_SERVICE_NAME
              value: cartservice

