apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  type: {{ .Values.cartservice.service.type }}
  selector:
    app: cartservice
  ports:
    - port: {{ .Values.cartservice.service.port }}
      targetPort: 8080

